### ISSUE TITLE
Not working as expected...

### ISSUE THREAD

**Issue by rajashekhargundeti** [kripken/xml.js#14]
Hi,

I'm able to successfully compile it on ubuntu 14. but when i execute the following code, it is getting terminated without  spitting any error, below is my code:

`fs = require('fs');
xml1 = fs.readFileSync('./test/test.xml');
xsd1 = fs.readFileSync('./test/test.xsd');
xmllint = eval(''+fs.readFileSync('./xmllint.js'));
result = xmllint.validateXML({xml: xml1.toString(), schema: xsd1.toString()});
console.log("result: " + result);`

my test.xml is : 

<?xml version="1.0"?>
<x:books xmlns:x="urn:books">
   <book id="bk001">
      <author>Writer</author>
      <title>The First Book</title>
      <genre>Fiction</genre>
      <price>44.95</price>
      <pub_date>2000-10-01</pub_date>
      <review>An amazing story of nothing.</review>
   </book>

   <book id="bk002">
      <author>Poet</author>
      <title>The Poet's First Poem</title>
      <genre>Poem</genre>
      <price>24.95</price>
      <pub_date>2000-10-01</pub_date>
      <review>Least poetic poems.</review>
   </book>
    
</x:books>

my xsd is:

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:books" xmlns:bks="urn:books">

	<xsd:element name="books" type="bks:BooksForm" />

	<xsd:complexType name="BooksForm">
		<xsd:sequence>
			<xsd:element name="book" type="bks:BookForm" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="BookForm">
		<xsd:sequence>
			<xsd:element name="author" type="xsd:string" />
			<xsd:element name="title" type="xsd:string" />
			<xsd:element name="genre" type="xsd:string" />
			<xsd:element name="price" type="xsd:float" />
			<xsd:element name="pub_date" type="xsd:date" />
			<xsd:element name="review" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" />
	</xsd:complexType>
</xsd:schema>

**Comment by sterpe** [comment]
Try 

xmllint = require('./xmllint.js')

**Comment by rajashekhargundeti** [comment]
I tried that approach first, same results.

**Comment by sterpe** [comment]
Can you set up a repo that reproduces the problem?

**Comment by sterpe** [comment]
Also, what happens if you don't build it from the source, and just use package available from `npm`: 
```
npm i xmllint
```
?

Emscripten changes quite a bit, it's possible that there have been breaking changes and this no longer compiles correctly with the latest version of emscripten SDK.

**Comment by sterpe** [comment]
This should compile correctly with emscripten SDK 1.29.0 see #4.

**Comment by rajashekhargundeti** [comment]
same result if i use xmllint module:

![image](https://cloud.githubusercontent.com/assets/11814052/16169699/0aab8502-3555-11e6-851c-b35c55a7abfd.png)



One thing that is working for me is : the code that i got from http://syssgx.github.io/xml.js/js/xmllint.js.

I took this and tried. it is working as expected. I have an issue with the script is that it is writing the output directly to the console, but i need to keep the result to include it in my project.

![image](https://cloud.githubusercontent.com/assets/11814052/16169704/71ec675e-3555-11e6-9a69-de918115add9.png)

**Comment by sterpe** [comment]
If you can put together a small repo that reproduces the issue I will look into this further.

**Comment by rajashekhargundeti** [comment]
https://github.com/rajashekhargundeti/xmllint-test


clone this repository and run server.js file

It is terminating the node process after validation.

**Comment by rajashekhargundeti** [comment]
I tested this with http module. same issue.

![image](https://cloud.githubusercontent.com/assets/11814052/16223962/8b4d41ae-37bd-11e6-827f-a47cab45e4a4.png)

contents of test file:

![image](https://cloud.githubusercontent.com/assets/11814052/16223978/a5ced09c-37bd-11e6-984b-428e1f14de37.png)


It is crashing the node process with this exception: 

gundetir@gundetir-VirtualBox:~/workspace/nodejs/client/test$ node http-test.js
Server is listening

result: {"errors":null}
Caught exception: TypeError: xmllint.validateXML is not a function
/media/sf_nodejs/client/node_modules/xmllint/xmllint.js:11
Module["preRun"]=(function(){var i;for(i=0;i<(1||Module["xml"].length);i++){FS.createDataFile("/","file_"+i+".xml",Module["intArrayFromString"](Module["xml"][i]),true,true)}for(i=0;i<Module["schema"].length;i++){FS.createDataFile("/","file_"+i+".xsd",Module["intArrayFromString"](Module["schema"][i]),true,true)}});Module.arguments=["--noout"];((function(){var i;if("[object Array]"!==Object.prototype.toString.call(Module["schema"])){Module["schema"]=[Module["schema"]]}if("[object Array]"!==Object.prototype.toString.call(Module["xml"])){Module["xml"]=[Module["xml"]]}for(i=0;i<Module["schema"].length;i++){Module.arguments.push("--schema");Module.arguments.push("file_"+i+".xsd")}for(i=0;i<(1||Module["xml"].length);i++){Module.arguments.push("file_"+i+".xml")}}))();Module["return"]="";Module["stdout"]=Module["stderr"]=(function(code){Module["return"]+=String.fromCharCode(code)});var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};va

TypeError: xmllint.validateXML is not a function
    at Server.<anonymous> (/media/sf_nodejs/client/test/http-test.js:10:22)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

**Comment by sterpe** [comment]
@rajashekhargundeti This seems to be similar to #11.  Unfortunately, I don't think anyone has a solution for this yet.  It looks like what you are trying to do is use xmllint on a server.  I would recommend using `child_process.spawn|exec` to shell out to the C version of xmllint.  It is far more powerful.

**Comment by sterpe** [comment]
It seems like certain types of `.xml` & .`xsd` can have problems because they specify pathing relative to each other but that pathing does not correspond to the virtualFS filesystem that `emscripten` uses

**Comment by sterpe** [comment]
http://syssgx.github.io/xml.js/js/xmllint.js was compiled with an earlier version of `emscripten` perhaps there have been internal changes.

**Comment by rondonjon** [comment]
Same problem here. I had added xmllint to my unit tests, and noticed that they started to terminate randomly. After removing xmllint, the problem was solved.

**Comment by italobologna** [comment]
Guess this is really an old topic, but I had the same issue with the node application and did a workaround to the problem by invoking a node child process to call the library.

Solution was mostly:

For the main code:
```js
  return new Promise(resolve => {
    const lint = fork(`${ __dirname }/xmllint.js`);
    lint.on('message', resolve);
    lint.send({ xml: xmlString, xsd: xsdString });
  });
```

As the auxiliary child process:
```js
const { validateXML } = require('xmllint');

const evaluateXml = (xml, xsd) => {
  return validateXML({ xml: xml, schema: xsd });
};

process.on('message', ({ xml, xsd }) => {
  process.send(evaluateXml(xml, xsd));
});
```

**Comment by Beat-YT** [comment]
You can use my fork https://github.com/Beat-YT/xml.js
