### ISSUE TITLE
Updating libxml to v2.9.8 doesn't run properly (Module.intArrayFromString is not a function)

### ISSUE THREAD

**Issue by yulrizka** [kripken/xml.js#22]
I manage to recompile xmllint.js with:

```
Writing .emscripten configuration file to user home directory /Users/myuser/
The Emscripten configuration file /Users/myuser/.emscripten has been rewritten with the following contents:

import os
LLVM_ROOT='/Users/myuser/dev/node/emsdk/clang/e1.37.36_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/Users/myuser/dev/node/emsdk/clang/e1.37.36_64bit/optimizer'
BINARYEN_ROOT='/Users/myuser/dev/node/emsdk/clang/e1.37.36_64bit/binaryen'
NODE_JS='/Users/myuser/dev/node/emsdk/node/8.9.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/Users/myuser/dev/node/emsdk/emscripten/1.37.36'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/var/folders/1b/t4x1219d0kxfrn2qjlwcbwmm09rlyv/T'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.

   /Users/myuser/dev/node/emsdk:/Users/myuser/dev/node/emsdk/clang/e1.37.36_64bit:/Users/myuser/dev/node/emsdk/node/8.9.1_64bit/bin:/Users/myuser/dev/node/emsdk/emscripten/1.37.36
Set the following tools as active:
   clang-e1.37.36-64bit
   node-8.9.1-64bit
   emscripten-1.37.36
```

After I upgrade libxml to the latest, test run fine

https://github.com/yulrizka/xml.js/commit/77fd70358684c8794e4f2f7f3d714b861451d996

```
$ ./script/test
WARNING:root:object /private/var/folders/1b/t4x1219d0kxfrn2qjlwcbwmm09rlyv/T/emscripten_temp__9GPaX_archive_contents/#_LLVM_SYM_TAB_# is not valid, cannot link
./test/test.xml validates
```

But running the `test.js` give the this output
```
$ node test.js
/Users/myuser/dev/node/xml.js/xmllint.js:12
var Module=typeof Module!=="undefined"?Module:{};Module["preRun"]=(function(){var i;for(i=0;i<(1||Module["xml"].length);i++){FS.createDataFile("/","file_"+i+".xml",Module["intArrayFromString"](Module["xml"][i]),true,true)}for(i=0;i<Module["schema"].length;i++){FS.createDataFile("/","file_"+i+".xsd",Module["intArrayFromString"](Module["schema"][i]),true,true)}});Module.arguments=["--nonet","--nowarning","--dropdtd","--noent"];((function(){var i;if("[object Array]"!==Object.prototype.toString.call(Module["schema"])){Module["schema"]=[Module["schema"]]}if("[object Array]"!==Object.prototype.toString.call(Module["xml"])){Module["xml"]=[Module["xml"]]}for(i=0;i<Module["schema"].length;i++){Module.arguments.push("--schema");Module.arguments.push("file_"+i+".xsd")}for(i=0;i<(1||Module["xml"].length);i++){Module.arguments.push("file_"+i+".xml")}}))();Module["return"]="";Module["stdout"]=Module["stderr"]=(function(code){Module["return"]+=String.fromCharCode(code)});var

TypeError: Module.intArrayFromString is not a function
    at Module.preRun (/Users/myuser/dev/node/xml.js/xmllint.js:12:193)
    at callRuntimeCallbacks (/Users/myuser/dev/node/xml.js/xmllint.js:12:14982)
    at preRun (/Users/myuser/dev/node/xml.js/xmllint.js:12:15541)
    at run (/Users/myuser/dev/node/xml.js/xmllint.js:47:5194)
    at Object.xmllint.validateXML (/Users/myuser/dev/node/xml.js/xmllint.js:47:6579)
    at Object.<anonymous> (/Users/myuser/dev/node/xml.js/test/test.js:7:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

I also checked the source and compare the output of xmllint.js, it seems that `intArrayFromString` indeed not generated by the newly compiled version.

Do you maybe have any idea why?

**Comment by kripken** [comment]
Looks like https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-i-get-typeerror-module-something-is-not-a-function - that method is no longer exported by default in emscripten, so you need to add it to `EXTRA_EXPORTED_RUNTIME_METHODS` as described there.

**Comment by yulrizka** [comment]
Works, thanks 👍
